### ISSUE TITLE
new wheel version break wheel-axle

### ISSUE THREAD

**Issue by biggysmith** [karellen/wheel-axle#22]
my autobuild has just started breaking:

Successfully installed filelock-3.15.4 **wheel-0.44.0** wheel-axle-0.0.7 wheel-axle-runtime-0.0.5

+ python3.10 setup.py bdist_axle
Traceback (most recent call last):
  File "/setup.py", line 317, in <module>
    setup(
  File "/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 171, in setup
    ok = dist.parse_command_line()
  File "/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 478, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/venv/lib/python3.10/site-packages/setuptools/dist.py", line 847, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 537, in _parse_command_opts
    cmd_class = self.get_command_class(command)
  File "/venv/lib/python3.10/site-packages/setuptools/dist.py", line 692, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/venv/lib/python3.10/site-packages/wheel_axle/bdist_axle/__init__.py", line 35, in <module>
    from wheel.bdist_wheel import bdist_wheel as _bdist_wheel, python_tag
ImportError: cannot import name 'python_tag' from 'wheel.bdist_wheel' (/venv/lib/python3.10/site-packages/wheel/bdist_wheel.py)

started happening after it started using wheel version 0.44.0.

I can workaround by downgrading to wheel version 0.43.0, but I thought you should know.

**Comment by arcivanov** [comment]
Fixed in v0.0.8

**Comment by biggysmith** [comment]
great! :)
